// Woven — typed graph schema. The single source for node/edge shapes.
// Mirrors ARCHITECTURE.md §1. Pages read this graph through lib/api.ts instead of
// hard-coding arrays, so the prototype runs on the real model — swap lib/api.ts for
// real fetch() calls later and it goes live.

export type ProvState = "user_created" | "ai_generated" | "human_verified";
export type ArtifactState = "processing" | "living" | "archived";
export type ArtifactType = "HTML" | "MD" | "DOC";

// ——————————————————————————————————————————— nodes

export type Artifact = {
  id: string;
  type: ArtifactType;
  title: string;
  state: ArtifactState;
  prov: ProvState; // who created it (agent capture → ai_generated by default)
  space_id: string; // permission boundary
  collection_ids: string[];
  author_id: string; // person id | "agent"
  public: boolean; // independently published as its own /a/ page
  hub_slug?: string; // set when published
  // presentation fields kept on the node so views stay declarative (the prototype's
  // pragmatic shortcut — a real backend would derive gist/scale from body + analytics):
  gist: string; // one-line "what it is" (HTML card sub-line + public hub blurb)
  summary?: string; // longer excerpt (MD/DOC card cover)
  scale?: string; // "820 words · 3 sections" (MD/DOC card sub-line)
  updated: string; // relative label for the prototype ("17m")
  // living-artifact freshness — the prototype states staleness explicitly; a real backend would derive it
  // by propagating a source/dependency's change through the graph. (Superseding is derived from the edge.)
  staleness?: { source_label: string; since: string };
};

export type Block = {
  id: string;
  artifact_id: string;
  anchor: string; // → artifact#anchor (the citable sub-node)
  heading: string;
  text: string;
  // optional embedded figure — the selection-aware editor treats it as an image target
  // (Replace / Enlarge / Caption). `altSrc` is the swap target for "Replace".
  image?: { src: string; altSrc?: string; caption: string; alt: string };
  // a callout block — a light structural template (agent-prefilled or user-added); renders as a tinted
  // box instead of a heading+paragraph, and is left out of the outline.
  callout?: { tone: CalloutTone };
};

export type CalloutTone = "insight" | "note" | "warning";

export type Person = { id: string; name: string; role: string; initial: string };
export type Topic = { id: string; name: string };
export type Decision = { id: string; text: string; artifact_id: string };
// external provenance (transcripts, syncs, audits) — what a node was woven FROM.
// A light extension to ARCHITECTURE §1 so `sourced_from` can point outside the graph.
export type Source = {
  id: string;
  label: string;
  kind: "transcript" | "meeting" | "audit" | "doc";
  at?: string; // when it was captured (relative label, prototype)
  note?: string; // one-line "what it contributed" — surfaced in the source peek
};

export type CollectionKind = "typed" | "simple";
export type Collection = {
  id: string;
  slug: string;
  name: string;
  color: string;
  space_id: string;
  public: boolean;
  kind: CollectionKind;
  intro?: string; // public-hub blurb
  public_member_ids: string[]; // the subset chosen for the public hub
  member_order?: string[]; // curated member order (artifact ids); absent/partial = the rest keep default order
};

export type SpaceKind = "personal" | "team" | "org";
export type Space = {
  id: string;
  name: string;
  kind: SpaceKind;
  visibility: "open" | "closed" | "private";
};

// ——————————————————————————————————————————— edges (typed, directional)

export type EdgeType =
  | "links_to" // artifact → artifact | collection | topic
  | "sourced_from" // artifact → artifact | block | source  (provenance)
  | "mentions" // artifact → person | topic
  | "in_collection" // artifact → collection
  | "authored_by" // artifact → person | "agent"
  | "decided" // artifact → decision
  | "supersedes"; // artifact | decision → …

export type Edge = {
  id: string;
  type: EdgeType;
  from: string;
  to: string;
  prov: ProvState; // ai_generated = pending the Verify queue
  confidence?: number; // sorts the queue; never shown as a % (confidence is a valve, not a number)
  rationale?: string; // the agent's plain-language reason — shown in the Verify queue in place of a %
  anchor?: string; // the block this edge supports — section-level provenance for the evidence rail
  created_by: string; // person id | "agent"
};

// ——————————————————————————————————————————— view-models (what api resolves to)

// a resolved relation row (artifact rail rows / linked refs)
export type RefKind = "artifact" | "collection" | "topic" | "source" | "person" | "decision";
export type Ref = { id: string; label: string; kind: RefKind };

// card "connections" descriptor — UI maps kind → icon, keeping lib free of React/lucide
export type ConnKind = "link" | "people" | "sources" | "version";
export type Conn = { kind: ConnKind; label: string };

// a pending agent-proposed edge (the Verify trust mechanism)
export type Proposed = { edge_id: string; label: string; target_id: string; kind?: RefKind; confidence?: number; rationale?: string };

// the artifact's resolved graph rail
export type ArtifactGraph = {
  proposed: Proposed[];
  linkedTo: Ref[];
  linkedFrom: Ref[];
  sources: Ref[];
  people: Person[];
  decisions: Decision[];
};

// the read-along evidence rail — provenance shown beside the body, each item anchored to a section
export type EvidenceGroup = "proposed" | "source" | "person" | "topic" | "decision" | "link";
export type EvidenceItem = {
  edge_id: string;
  group: EvidenceGroup;
  label: string;
  target_id: string;
  kind: RefKind;
  prov: ProvState;
  rationale?: string;
  block_id?: string; // the section (block) this evidence supports; absent = whole-artifact
  href?: string; // navigable target (an artifact)
};

// activity feed event
export type Activity = {
  id: string;
  initial: string;
  agent: boolean;
  actor?: string; // person id — seeds the avatar hue so the same person matches everywhere
  text: string;
  t: string;
  href?: string; // where the row jumps to (resume / see the change) — a change feed, not a dead log
  sub?: string; // an agent row's "what it actually did" (linked N sources · named · filed)
};

// an item that needs the user — surfaced above the Recent feed on Today (derived, not stored)
export type NeedItem = {
  id: string;
  kind: "proposal" | "stale" | "candidate" | "capture";
  title: string;
  sub: string;
  href: string;
  action: string; // the inline verb — "Verify" | "Review"
};

// analytics (artifact Audience + collection dual analytics)
export type Stat = { v: string; l: string };
export type ReadRow = { h: string; pct: number };
export type ReaderRow = { i: string; n: string; t: string; ext: boolean };
export type Analytics = {
  url?: string;
  stats: Stat[];
  readthrough: ReadRow[]; // by section (artifact) | most-read (collection)
  readers: ReaderRow[];
};

// Ask over a single artifact — a cited answer whose citations are live graph anchors
// (block_id scrolls to the section; href navigates to another artifact in the neighborhood).
export type AskCite = { label: string; block_id?: string; href?: string };
export type ArtifactAsk = { answer: string; cites: AskCite[] };

// living-artifact freshness — superseded (a newer artifact replaced this, via the supersedes edge) beats
// stale (a source this was woven from has since changed); otherwise fresh.
export type Freshness =
  | { state: "fresh" }
  | { state: "stale"; source_label: string; since: string }
  | { state: "superseded"; by_id: string; by_label: string };

// ——————————————————————————————————————————— KG-viz (local graph, the "show me" affordance)

// a node in a focused neighborhood (depth-bounded, never the global graph)
export type GraphNode = {
  id: string;
  label: string;
  kind: RefKind;
  type?: ArtifactType; // for artifacts — drives the dot glyph
  state?: ArtifactState;
  prov?: ProvState;
  depth: number; // 0 = the focused center, 1–2 = neighborhood rings
};
export type GraphEdge = {
  id: string;
  from: string;
  to: string;
  type: EdgeType;
  prov: ProvState; // ai_generated → drawn dashed (provisional until verified)
  confidence?: number;
};
export type Neighborhood = { centerId: string; nodes: GraphNode[]; edges: GraphEdge[] };

// the paired Links list (graph is always paired with a list)
export type GraphRel = {
  edge_id: string;
  target_id: string; // the other node — click a row to re-center on it
  label: string;
  kind: RefKind;
  edgeType: EdgeType;
  prov: ProvState;
  dir: "out" | "in";
  confidence?: number;
};

// a stat row for the node preview/inspector
export type NodeStat = { label: string; value: string };

// ——————————————————————————————————————————— conversational edit (③, P1 single-player)

// an agent-proposed change to a block — the content-level three-state valve
// (proposed → Accept makes it human_verified, Reject discards). Mirrors ARCHITECTURE §2.1
// POST /artifacts/:id/instruct → { proposed_diff }.
export type EditProposalKind = "rewrite" | "tone" | "add";
export type EditProposal = {
  id: string;
  artifact_id: string;
  instruction: string; // the chip label / the user's typed instruction
  kind: EditProposalKind;
  block_id: string; // an existing block (rewrite/tone) or a new anchor (add)
  heading?: string; // section heading (shown for add; labels the target for rewrite/tone)
  before?: string; // current text (rewrite/tone) — absent for add
  after: string; // proposed text
  keywords?: string[]; // free-text routing
};

// ——————————————————————————————————————————— verify queue (the three-state trust valve)

// a resolved ai_generated edge awaiting human verification (Inbox row)
export type PendingEdge = {
  edge_id: string;
  type: EdgeType;
  fromId: string;
  fromLabel: string;
  fromKind: RefKind;
  toId: string;
  toLabel: string;
  toKind: RefKind;
  confidence: number;
  rationale?: string; // the agent's plain-language "why" — replaces the confidence %
};

// ——————————————————————————————————————————— capture review (the post-capture trust valve)
export type ReviewKind = "duplicate" | "naming" | "archive" | "extraction";
export type ReviewAction = { id: string; label: string; primary?: boolean };
// a decision the agent surfaces in the Inbox after a capture — adjudicated with a multi-choice valve
export type CaptureReview = {
  id: string;
  kind: ReviewKind;
  title: string; // the dropped artifact (or the conflict's subject)
  detail: string; // the agent's plain-language finding
  actions: ReviewAction[]; // the valve choices; the first is the primary
  // for kind "duplicate" — the two artifacts the Merge valve reconciles ([dropped, existing]). The
  // merge sheet lets the user pick which survives as canonical; the other is archived and its
  // connections move onto the survivor.
  dupeArtifactIds?: [string, string];
};

// a smart-collection membership the agent proposes — "artifact X belongs in collection Y" — adjudicated
// in the Inbox; confirming actually pushes the collection onto the artifact's collection_ids.
export type CollectionCandidate = {
  id: string;
  collectionId: string;
  collectionName: string;
  artifactId: string;
  artifactTitle: string;
  rationale: string; // why the agent thinks it fits (matched against the collection's rule)
};

// ——————————————————————————————————————————— episodic memory (the social narrative over the graph)
// The typed graph is SEMANTIC memory (what's true, what connects to what). Episodes are EPISODIC memory —
// the time-stamped record of "what happened, when, who, why". The key move: a human confirming an edge in
// the Verify queue IS an episode, so the semantic edge (Edge.prov → human_verified) and its episodic record
// (a "confirmed" Episode carrying that edgeId) are written in one flow.
export type EpisodeKind =
  | "captured" // the agent wove the drop into an artifact
  | "proposed" // the agent proposed edge(s) to verify
  | "confirmed" // a human verified a proposed edge (the confirm-event — semantic + episodic in one)
  | "commented" // someone opened or added to a discussion
  | "resolved" // a discussion was settled
  | "edited" // a block was changed
  | "superseded"; // a version rolled — a newer artifact replaced an older one
export type Episode = {
  id: string;
  artifactId: string;
  kind: EpisodeKind;
  actor: string; // person id | "agent"
  at: string; // relative label e.g. "2h"
  summary: string; // human-narrated line — "Maya confirmed the link to …", not a raw log row
  edgeId?: string; // the semantic edge this episode is about (set on proposed/confirmed)
  blockId?: string; // the section this episode touched (absent = whole-artifact)
  discussionId?: string; // the thread this episode is about (set on commented/resolved)
};

// ——————————————————————————————————————————— discussions (durable, rebuilt from ephemeral chat)
// Comments are no longer transient chat — they persist as Discussion objects. A `decision`-tagged thread
// is the provenance for a decision (the thread OWNS the "why" behind it). A comment can carry a suggestion:
// a concrete before/after on a block, the discussion-native sibling of the agent's EditProposal.
export type CommentKind = "comment" | "suggestion";
export type Comment = {
  id: string;
  author: string; // person id
  text: string;
  at: string; // relative label
  kind: CommentKind;
  suggestion?: { blockId: string; before: string; after: string }; // set when kind === "suggestion"
};

export type DiscussionStatus = "open" | "resolved";
export type DiscussionTag = "decision" | "question" | "todo";
export type Discussion = {
  id: string;
  artifactId: string;
  blockId?: string; // the section it hangs off (absent = whole-artifact thread)
  status: DiscussionStatus;
  tag?: DiscussionTag;
  title: string;
  participants: string[]; // person ids who have weighed in
  createdAt: string; // relative label
  comments: Comment[];
};
